//每題有幾個選項
numberOfOptions = 4;

//每列最多可以有幾個選項
numberOfOptionsPerRow = 2;	

//是否自動顯示選項供作答(預設為 true; false 時需按[開始作答]鈕才會出現選項)
auto_show_options = true;

//每回合抽幾題題目
numberOfQuestionsPerRound = 50;

//出題時選擇題目的方式 true:亂數選題  false:按題庫順序
select_questions_in_random = true; 


//聲音檔路徑的前置網址
//也就是會為 questionLines 的左欄前面自動加上的字串
//
// English 1200
soundBaseURL = 'https://gsyan888.github.io/english1200/';


//語音播放的速度(使用大於 0 的數字。例如:1.0 正常, 0.75 較慢速, 0.5 慢速, 1.5 快速, 2.0 兩倍速)
audioPlaybackRate = 1.0; 

//語音自動播放的次數。 
audioAutoPlayLoop = 1;

//隔多久重播(單位秒)
audioAutoPlayDelay = 0;


//是否使用 TTS 的語音
tts_enabled = false;

//----------------
//Google TTS 文字轉語音的設定
//----------------
tts_language = 'en';  // en : 英語,   zh_tw : 中文
tts_speed = 0.3;  //語音的速度 0 ~ 1 (可用小數)
tts_base_url = 'https://translate.google.com/translate_tts?ie=UTF-8&tl='+tts_language+'&client=tw-ob&ttsspeed='+tts_speed+'&q=';


//題庫
//欄位分隔符號為兩個井字號(##)
seperator = '##';

//左欄為聲音檔路徑
//右欄為中文
questionLines = function(){/*--這一行請勿更改--
letter_a/sounds/a_few.mp3##adj.一些(接可數名詞)
letter_a/sounds/a_little.mp3##adj.一些(接不可數名詞)
letter_a/sounds/a_lot.mp3##adv.許多
letter_a/sounds/able.mp3##adj.能夠
letter_a/sounds/about.mp3##prep.大約關於
letter_a/sounds/above.mp3##prep.在..上方
letter_a/sounds/afraid.mp3##adj.害怕的
letter_a/sounds/after.mp3##prep.conj.在~之後
letter_a/sounds/afternoon.mp3##n.下午
letter_a/sounds/again.mp3##Adv.再一次
letter_a/sounds/age.mp3##n.年齡
letter_a/sounds/ago.mp3##Adv.以前
letter_a/sounds/agree.mp3##v.同意
letter_a/sounds/air.mp3##n.空氣
letter_a/sounds/airplane(plane).mp3##n.飛機
letter_a/sounds/airport.mp3##n.飛機場
letter_a/sounds/all.mp3##adj.全部的
letter_a/sounds/almost.mp3##Adv.幾乎
letter_a/sounds/along.mp3##prep.沿著
letter_a/sounds/already.mp3##Adv.已經
letter_a/sounds/also.mp3##Adv.也
letter_a/sounds/always.mp3##Adv.總是
letter_a/sounds/a.m..mp3##Abrr.午前
letter_a/sounds/America.mp3##n.美國
letter_a/sounds/American.mp3##n.美國人
letter_a/sounds/a(an).mp3##art.一個
letter_a/sounds/and.mp3##conj.而且
letter_a/sounds/angel.mp3##n.天使
letter_a/sounds/angry.mp3##adj.生氣的
letter_a/sounds/animal.mp3##n.動物
letter_a/sounds/another.mp3##Pron.其他的
letter_a/sounds/answer.mp3##n.答案v.回答
letter_a/sounds/any.mp3##adj.任何
letter_a/sounds/anyone(anybody).mp3##Pron.任何人
letter_a/sounds/anything.mp3##Pron.任何事
letter_a/sounds/apartment.mp3##n.公寓
letter_a/sounds/apologize.mp3##v.道歉
letter_a/sounds/appear.mp3##v.出現
letter_a/sounds/apple.mp3##n.蘋果
letter_a/sounds/April.mp3##n.四月
letter_a/sounds/argue.mp3##v.爭辯
letter_a/sounds/arm.mp3##n.手臂
letter_a/sounds/army.mp3##n.軍隊
letter_a/sounds/around.mp3##adv.圍繞四周
letter_a/sounds/arrive.mp3##v.到達
letter_a/sounds/art.mp3##v.藝術
letter_a/sounds/as.mp3##pron.Conj.像~一樣
letter_a/sounds/ask.mp3##v.詢問
letter_a/sounds/asleep.mp3##adj.睡著
letter_a/sounds/at.mp3##Prep.在(時間)
letter_a/sounds/August.mp3##n.八月
letter_a/sounds/aunt.mp3##n.姑姑嬸嬸阿姨
letter_a/sounds/autumn(fall).mp3##n.秋天
letter_a/sounds/available.mp3##adj.有效的
letter_a/sounds/away.mp3##adv.離開
letter_b/sounds/baby.mp3##n.嬰兒
letter_b/sounds/back.mp3##adv.回來
letter_b/sounds/backward.mp3##adj.向後的
letter_b/sounds/bad.mp3##adj.壞的
letter_b/sounds/bag.mp3##n.袋子
letter_b/sounds/bakery.mp3##n.麵包店
letter_b/sounds/ball.mp3##n.球
letter_b/sounds/balloon.mp3##n.汽球
letter_b/sounds/banana.mp3##n.香蕉
letter_b/sounds/band.mp3##n.樂團
letter_b/sounds/bank.mp3##n.銀行
letter_b/sounds/barbecue.mp3##v.;n.烤肉
letter_b/sounds/base.mp3##n.底部;根基
letter_b/sounds/baseball.mp3##n.棒球
letter_b/sounds/basic.mp3##adj.基礎的
letter_b/sounds/basket.mp3##n.籃子
letter_b/sounds/basketball.mp3##n.籃球
letter_b/sounds/bath.mp3##n.洗澡
letter_b/sounds/bathe.mp3##v.沐浴;浸濕
letter_b/sounds/bathroom.mp3##n.浴室
letter_b/sounds/be(am, are, is, was, were, been).mp3##v.是
letter_b/sounds/beach.mp3##n.沙灘
letter_b/sounds/bear.mp3##v.;n.承受;熊
letter_b/sounds/beautiful.mp3##adj.美麗的
letter_b/sounds/beauty.mp3##n.美貌;美人
letter_b/sounds/because.mp3##conj.因為
letter_b/sounds/become.mp3##v.變成
letter_b/sounds/bed.mp3##n.床
letter_b/sounds/bedroom.mp3##n.臥室
letter_b/sounds/beef.mp3##n.牛排
letter_b/sounds/before.mp3##conj.在~之前
letter_b/sounds/begin.mp3##v.開始
letter_b/sounds/beginner.mp3##n.初學者
letter_b/sounds/behind.mp3##prep.在~之後
letter_b/sounds/believe.mp3##v.相信
letter_b/sounds/bell.mp3##n.鐘
letter_b/sounds/belong.mp3##v.屬於
letter_b/sounds/below.mp3##prep.在~之下
letter_b/sounds/belt.mp3##n.帶子
letter_b/sounds/beside.mp3##prep.在~旁邊
letter_b/sounds/besides.mp3##prep.而且除了~之外
letter_b/sounds/between.mp3##prep.在~中間
letter_b/sounds/beyond.mp3##prep.(指品質等)超脫於
letter_b/sounds/bicycle(bike).mp3##n.腳踏車
letter_b/sounds/big.mp3##adj.大的
letter_b/sounds/bike.mp3##n.腳踏車
letter_b/sounds/biology.mp3##n.生物學
letter_b/sounds/bird.mp3##n.小鳥
letter_b/sounds/birthday.mp3##n.生日
letter_b/sounds/bite.mp3##v.咬
letter_b/sounds/black.mp3##adj.黑色
letter_b/sounds/blackboard.mp3##n.黑板
letter_b/sounds/blame.mp3##v.責備
letter_b/sounds/blind.mp3##adj.失明的
letter_b/sounds/block.mp3##n.;v.街區;阻擋
letter_b/sounds/blood.mp3##n.血液
letter_b/sounds/blow.mp3##v.吹
letter_b/sounds/blue.mp3##n.;adj.藍色;憂鬱的
letter_b/sounds/boat.mp3##n.船
letter_b/sounds/body.mp3##n.身體
letter_b/sounds/book.mp3##n.書
letter_b/sounds/bookstore.mp3##n.書店
letter_b/sounds/bored.mp3##adj.感到無聊的
letter_b/sounds/boring.mp3##adj.令人無聊的
letter_b/sounds/born.mp3##v.出生
letter_b/sounds/borrow.mp3##v.借
letter_b/sounds/boss.mp3##n.老闆
letter_b/sounds/both.mp3##pron.兩者都
letter_b/sounds/bother.mp3##v.打擾
letter_b/sounds/bottle.mp3##n.瓶子
letter_b/sounds/bottom.mp3##n.底部
letter_b/sounds/bowl.mp3##n.碗
letter_b/sounds/box.mp3##n.箱子
letter_b/sounds/boy.mp3##n.男孩
letter_b/sounds/bread.mp3##n.麵包
letter_b/sounds/break.mp3##v.;n.打破;休息
letter_b/sounds/breakfast.mp3##n.早餐"
letter_b/sounds/bridge.mp3##n.橋樑
letter_b/sounds/bright.mp3##adj.明亮的
letter_b/sounds/bring.mp3##v.帶
letter_b/sounds/brother.mp3##n.兄弟
letter_b/sounds/brown.mp3##adj.棕色的
letter_b/sounds/brush.mp3##v.刷
letter_b/sounds/build.mp3##v.建造
letter_b/sounds/burn.mp3##v.燃燒
letter_b/sounds/bus.mp3##n.公車
letter_b/sounds/business.mp3##n.生意
letter_b/sounds/businessman.mp3##n.生意人
letter_b/sounds/busy.mp3##adj.忙碌的
letter_b/sounds/but.mp3##conj.但是
letter_b/sounds/butter.mp3##n.奶油
letter_b/sounds/button.mp3##n.按鈕
letter_b/sounds/buy.mp3##v.買
letter_b/sounds/by.mp3##prep.1)在~旁邊2)搭乘3)藉著
letter_c/sounds/cake.mp3##n.蛋糕
letter_c/sounds/call.mp3##v.打電話
letter_c/sounds/camera.mp3##n.相機
letter_c/sounds/camp.mp3##v.露營
letter_c/sounds/can_could.mp3##modalv.能夠
letter_c/sounds/candy.mp3##n.糖果
letter_c/sounds/cap.mp3##n.鴨舌帽
letter_c/sounds/car.mp3##n.車子
letter_c/sounds/card.mp3##n.卡片
letter_c/sounds/care.mp3##v.關心，在乎
letter_c/sounds/careful.mp3##adj.小心的
letter_c/sounds/carry.mp3##v.搬運,攜帶
letter_c/sounds/cartoon.mp3##n.卡通
letter_c/sounds/case.mp3##n.情形,盒，箱
letter_c/sounds/cat.mp3##n.貓
letter_c/sounds/catch.mp3##v.抓到
letter_c/sounds/cause.mp3##v.引起，造成
letter_c/sounds/celebrate.mp3##v.慶祝
letter_c/sounds/cell_phone.mp3##n.手機
letter_c/sounds/cent.mp3##n.分
letter_c/sounds/center.mp3##n.中心
letter_c/sounds/century.mp3##n.世紀
letter_c/sounds/certain.mp3##adj.確定的
letter_c/sounds/chair.mp3##n.椅子
letter_c/sounds/chalk.mp3##n.粉筆
letter_c/sounds/chance.mp3##n.機會
letter_c/sounds/change.mp3##v.改變
letter_c/sounds/chart.mp3##n.圖
letter_c/sounds/cheap.mp3##adj.便宜的
letter_c/sounds/cheat.mp3##v.作弊，欺騙
letter_c/sounds/check.mp3##v.檢查
letter_c/sounds/cheer.mp3##v.歡呼
letter_c/sounds/cheese.mp3##n.乳酪
letter_c/sounds/chemistry.mp3##n.化學
letter_c/sounds/chicken.mp3##n.雞肉
letter_c/sounds/child.mp3##n.孩子
letter_c/sounds/childhood.mp3##n.童年
letter_c/sounds/China.mp3##n.中國
letter_c/sounds/chinese.mp3##adj.中國的
letter_c/sounds/chocolate.mp3##n.巧克力
letter_c/sounds/choice.mp3##n.選擇
letter_c/sounds/chopsticks.mp3##n.筷子
letter_c/sounds/christmas.mp3##n.聖誕節
letter_c/sounds/church.mp3##n.教堂
letter_c/sounds/circle.mp3##n.v.圓圈
letter_c/sounds/city.mp3##n.城市
letter_c/sounds/class.mp3##n.班，課
letter_c/sounds/classmate.mp3##n.同班同學
letter_c/sounds/classroom.mp3##n.教室
letter_c/sounds/clean.mp3##v.清掃
letter_c/sounds/clear.mp3##adj.乾淨的
letter_c/sounds/climb.mp3##v.爬
letter_c/sounds/clock.mp3##n.時鐘
letter_c/sounds/close.mp3##v.關
letter_c/sounds/clothes.mp3##n.衣服
letter_c/sounds/cloud.mp3##n.雲
letter_c/sounds/cloudy.mp3##adj.多雲的
letter_c/sounds/club.mp3##n.社團
letter_c/sounds/coast.mp3##n.海岸
letter_c/sounds/coat.mp3##n.外套
letter_c/sounds/coffee.mp3##n.咖啡
letter_c/sounds/coke.mp3##n.可樂
letter_c/sounds/cold.mp3##adj.冷的
letter_c/sounds/collect.mp3##v.收集
letter_c/sounds/color.mp3##n.顏色
letter_c/sounds/colorful.mp3##adj.多采多姿
letter_c/sounds/come.mp3##v.來臨
letter_c/sounds/comfortable.mp3##adj.舒服的
letter_c/sounds/comic.mp3##adj.漫畫(的)
letter_c/sounds/common.mp3##adj.普通的
letter_c/sounds/computer.mp3##n.電腦
letter_c/sounds/concern.mp3##v.關心
letter_c/sounds/considerate.mp3##adj.體貼
letter_c/sounds/convenient.mp3##adj.便利的
letter_c/sounds/cook.mp3##v.烹飪；n.廚師
letter_c/sounds/cookie.mp3##n.餅乾
letter_c/sounds/cool.mp3##adj.v.涼快的；酷的；冷卻
letter_c/sounds/copy.mp3##v.n.影印，抄襲
letter_c/sounds/corner.mp3##n.轉角
letter_c/sounds/correct.mp3##adj.正確的
letter_c/sounds/cost.mp3##v.花費
letter_c/sounds/couch.mp3##n.沙發
letter_c/sounds/count.mp3##v.數
letter_c/sounds/country.mp3##n.國家
letter_c/sounds/cousin.mp3##n.堂(表)兄弟姊妹
letter_c/sounds/cover.mp3##n.封面
letter_c/sounds/cow.mp3##n.母牛
letter_c/sounds/cowboy.mp3##n.牛仔
letter_c/sounds/crayon.mp3##n.臘筆
letter_c/sounds/crazy.mp3##adj.瘋狂的
letter_c/sounds/cross.mp3##v.經過n.十字架
letter_c/sounds/cry.mp3##v.哭
letter_c/sounds/cup.mp3##n.杯子
letter_c/sounds/current.mp3##adj.現在的
letter_c/sounds/cut.mp3##v.切
letter_c/sounds/cute.mp3##adj.可愛的
letter_d/sounds/dance.mp3##v.跳舞
letter_d/sounds/dangerous.mp3##n.危險的
letter_d/sounds/dark.mp3##adj.黑暗的
letter_d/sounds/date.mp3##n.日期
letter_d/sounds/daughter.mp3##n.女兒
letter_d/sounds/dawn.mp3##n.黎明
letter_d/sounds/day.mp3##n.日子
letter_d/sounds/dead.mp3##adj.死亡的
letter_d/sounds/dear.mp3##adj.親愛的
letter_d/sounds/December.mp3##n.十二月
letter_d/sounds/decide.mp3##v.決定
letter_d/sounds/decrease.mp3##v;n.減少
letter_d/sounds/delicious.mp3##adj.好吃的
letter_d/sounds/department_store.mp3##n.百貨公司
letter_d/sounds/describe.mp3##v.形容描述
letter_d/sounds/desk.mp3##n.書桌
letter_d/sounds/develop.mp3##v.發展
letter_d/sounds/dictionary.mp3##n.字典
letter_d/sounds/die.mp3##v.死
letter_d/sounds/diet.mp3##n.節食
letter_d/sounds/different.mp3##adj.不同的
letter_d/sounds/difficult.mp3##adj.困難的
letter_d/sounds/dig.mp3##v.挖
letter_d/sounds/dining_room.mp3##n.飯廳
letter_d/sounds/dinner.mp3##n.晚餐
letter_d/sounds/dinosaur.mp3##n.恐龍
letter_d/sounds/diplomat.mp3##n.外交官
letter_d/sounds/dirty.mp3##adj.骯髒的
letter_d/sounds/discuss.mp3##v.討論
letter_d/sounds/dish.mp3##n.盤子
letter_d/sounds/distant.mp3##adj.遠離的
letter_d/sounds/divide.mp3##v.分割
letter_d/sounds/do.mp3##v.做
letter_d/sounds/doctor.mp3##n.醫生
letter_d/sounds/dog.mp3##n.狗
letter_d/sounds/doll.mp3##n.洋娃娃
letter_d/sounds/dollar.mp3##n.元
letter_d/sounds/door.mp3##n.門
letter_d/sounds/down.mp3##adv.向下
letter_d/sounds/dozen.mp3##n.(一)打
letter_d/sounds/dr.mp3##n.博士醫師
letter_d/sounds/draw.mp3##v.畫
letter_d/sounds/dream.mp3##v.作夢；夢想
letter_d/sounds/dress.mp3##n.洋裝
letter_d/sounds/drink.mp3##v.喝
letter_d/sounds/drive.mp3##v.開車
letter_d/sounds/driver.mp3##n.司機
letter_d/sounds/drop.mp3##v.掉落
letter_d/sounds/dry.mp3##adj.乾的
letter_d/sounds/during.mp3##prep.在~期間
letter_d/sounds/duty.mp3##n.職責
letter_e/sounds/each.mp3##adv.每一
letter_e/sounds/eagle.mp3##n.老鷹
letter_e/sounds/ear.mp3##n.耳朵
letter_e/sounds/early.mp3##adv.早
letter_e/sounds/ease.mp3##n.輕鬆v.舒緩
letter_e/sounds/east.mp3##n.東方
letter_e/sounds/easy.mp3##adj.簡單的
letter_e/sounds/eat.mp3##v.吃
letter_e/sounds/edge.mp3##n.邊緣
letter_e/sounds/education.mp3##n.教育
letter_e/sounds/effort.mp3##n.努力
letter_e/sounds/egg.mp3##n.蛋
letter_e/sounds/eight.mp3##n.八
letter_e/sounds/eighteen.mp3##n.十八
letter_e/sounds/eighth.mp3##n.第八
letter_e/sounds/eighty.mp3##n.八十
letter_e/sounds/either.mp3##adj.pron.也(不)
letter_e/sounds/electric.mp3##adj.電的
letter_e/sounds/elementary_school.mp3##n.小學
letter_e/sounds/elephant.mp3##n.大象
letter_e/sounds/eleven.mp3##n.十一
letter_e/sounds/else.mp3##adv.其他
letter_e/sounds/email.mp3##n.電子郵件
letter_e/sounds/embarrass.mp3##v.使~難堪
letter_e/sounds/empty.mp3##adj.空的
letter_e/sounds/end.mp3##n.結束
letter_e/sounds/energetic.mp3##adj.活力充沛
letter_e/sounds/english.mp3##n.英文
letter_e/sounds/enjoy.mp3##v.享受
letter_e/sounds/enough.mp3##adj.足夠
letter_e/sounds/enter.mp3##v.進入
letter_e/sounds/envy.mp3##v.羡慕
letter_e/sounds/equal.mp3##v.相等;等於
letter_e/sounds/eraser.mp3##n.橡皮擦
letter_e/sounds/eve.mp3##n.前夕
letter_e/sounds/even.mp3##adv.甚至
letter_e/sounds/evening.mp3##n.傍晚
letter_e/sounds/ever.mp3##adv.曾經
letter_e/sounds/every.mp3##adj.每一個
letter_e/sounds/everyone.mp3##pron.每一人
letter_e/sounds/everything.mp3##pron.每件事
letter_e/sounds/example.mp3##n.例子
letter_e/sounds/excellent.mp3##adj.優秀的
letter_e/sounds/except.mp3##prep.除~之外
letter_e/sounds/excited.mp3##adj.興奮的
letter_e/sounds/exciting.mp3##adj.刺激的
letter_e/sounds/excuse.mp3##n.藉口
letter_e/sounds/exercise.mp3##v.運動
letter_e/sounds/exist.mp3##v.存在
letter_e/sounds/exit.mp3##n.出口;退出
letter_e/sounds/expensive.mp3##adj.昂貴的
letter_e/sounds/experience.mp3##n.經驗
letter_e/sounds/eye.mp3##n.眼睛
letter_f/sounds/face.mp3##v.面對n.臉
letter_f/sounds/fact.mp3##n.事實
letter_f/sounds/factory.mp3##n.工廠
letter_f/sounds/fall.mp3##v.掉落
letter_f/sounds/false.mp3##adj.錯誤的
letter_f/sounds/family.mp3##n.家庭家人
letter_f/sounds/famous.mp3##adj.有名的
letter_f/sounds/fan.mp3##n.迷;電扇;扇子
letter_f/sounds/fancy.mp3##n.adj.幻想,想像的
letter_f/sounds/fantastic.mp3##adj.很棒的
letter_f/sounds/farm.mp3##n.農場
letter_f/sounds/farmer.mp3##n.農夫
letter_f/sounds/fashionable.mp3##adj.時髦的
letter_f/sounds/fast.mp3##adj.快速的
letter_f/sounds/fat.mp3##adj.肥的
letter_f/sounds/father.mp3##n.爸爸
letter_f/sounds/favorite.mp3##adj.最愛的
letter_f/sounds/february.mp3##n.二月
letter_f/sounds/fee.mp3##n.費用
letter_f/sounds/feed.mp3##v.餵;飼養
letter_f/sounds/feel.mp3##v.感覺
letter_f/sounds/female.mp3##n.女性
letter_f/sounds/festival.mp3##n.慶典
letter_f/sounds/few.mp3##pron.少數的
letter_f/sounds/fifteen.mp3##n.十五
letter_f/sounds/fifth.mp3##n.第五
letter_f/sounds/fifty.mp3##n.五十
letter_f/sounds/fill.mp3##v.充滿
letter_f/sounds/finally.mp3##adv.最後地
letter_f/sounds/find.mp3##v.找到
letter_f/sounds/fine.mp3##adj.很好
letter_f/sounds/finger.mp3##n.指頭
letter_f/sounds/finish.mp3##v.結束
letter_f/sounds/fire.mp3##n.火
letter_f/sounds/first.mp3##adv.第一首先
letter_f/sounds/fish.mp3##n.魚
letter_f/sounds/fisherman.mp3##n.漁夫
letter_f/sounds/five.mp3##n.五
letter_f/sounds/fix.mp3##v.修理
letter_f/sounds/flag.mp3##n.旗子
letter_f/sounds/floor.mp3##n.地板
letter_f/sounds/flower.mp3##n.花
letter_f/sounds/fly.mp3##v.飛
letter_f/sounds/follow.mp3##v.跟隨遵守
letter_f/sounds/food.mp3##n.食物
letter_f/sounds/foot.mp3##n.腳
letter_f/sounds/for.mp3##prep.給;為了
letter_f/sounds/foreign.mp3##adj.外國的
letter_f/sounds/foreigner.mp3##n.外國人
letter_f/sounds/forget.mp3##v.忘記
letter_f/sounds/fork.mp3##n.叉子
letter_f/sounds/formal.mp3##adj.正式的
letter_f/sounds/forty.mp3##n.四十
letter_f/sounds/forward.mp3##adj.adv.向前的;向前地
letter_f/sounds/four.mp3##n.四
letter_f/sounds/fourteen.mp3##n.十四
letter_f/sounds/fourth.mp3##n.第四
letter_f/sounds/free.mp3##adj.空閒的免費的
letter_f/sounds/fresh.mp3##adj.新鮮的
letter_f/sounds/Friday.mp3##n.星期五
letter_f/sounds/friend.mp3##n.朋友
letter_f/sounds/friendly.mp3##adj.友善的
letter_f/sounds/friendship.mp3##n.友誼
letter_f/sounds/from.mp3##prep.從~而來
letter_f/sounds/front.mp3##n.前面
letter_f/sounds/fruit.mp3##n.水果
letter_f/sounds/fry.mp3##v.炒;煎
letter_f/sounds/full.mp3##adj.充滿的
letter_f/sounds/fun.mp3##n.樂趣
letter_f/sounds/funny.mp3##adj.好笑的
letter_f/sounds/furniture.mp3##v.家具
letter_f/sounds/future.mp3##n.未來
letter_g/sounds/game.mp3##n.遊戲
letter_g/sounds/garbage.mp3##n.垃圾車
letter_g/sounds/garden.mp3##n.花園
letter_g/sounds/gas.mp3##n.瓦斯
letter_g/sounds/gather.mp3##v.團聚
letter_g/sounds/general.mp3##adj.普遍的;一般的
letter_g/sounds/genius.mp3##n.天才
letter_g/sounds/get.mp3##v.變成得到
letter_g/sounds/giant.mp3##n.巨人
letter_g/sounds/gift.mp3##n.禮物
letter_g/sounds/girl.mp3##n.女孩
letter_g/sounds/give.mp3##v.給
letter_g/sounds/glad.mp3##adj.高興的
letter_g/sounds/glass.mp3##n.玻璃杯
letter_g/sounds/glove.mp3##n.手套
letter_g/sounds/go.mp3##v.去
letter_g/sounds/goat.mp3##n.山羊
letter_g/sounds/good_bye.mp3##n.再見
letter_g/sounds/good.mp3##adj.好的
letter_g/sounds/grade.mp3##n.成績；級數
letter_g/sounds/gram.mp3##n.公克
letter_g/sounds/grandfather.mp3##n.祖父
letter_g/sounds/grandmother.mp3##n.祖母
letter_g/sounds/grass.mp3##n.草地
letter_g/sounds/gray.mp3##adj.灰色
letter_g/sounds/great.mp3##adj.很棒的
letter_g/sounds/green.mp3##adj.綠色
letter_g/sounds/ground.mp3##n.地板
letter_g/sounds/group.mp3##n.群
letter_g/sounds/grow.mp3##v.生長
letter_g/sounds/guess.mp3##v.猜
letter_h/sounds/habit.mp3##n.習慣
letter_h/sounds/hair.mp3##n.頭髮
letter_h/sounds/haircut.mp3##n.理頭髮
letter_h/sounds/half.mp3##n.一半
letter_h/sounds/ham.mp3##n.火腿
letter_h/sounds/hamburger.mp3##n.漢堡
letter_h/sounds/hand.mp3##n.手
letter_h/sounds/handsome.mp3##adj.英俊的
letter_h/sounds/hang.mp3##v.掛;吊
letter_h/sounds/happen.mp3##v.發生
letter_h/sounds/happy.mp3##adj.高興的
letter_h/sounds/hard.mp3##adj.困難的
letter_h/sounds/hard_working.mp3##adj.認真工作的
letter_h/sounds/hat.mp3##n.帽子
letter_h/sounds/hate.mp3##v.痛恨
letter_h/sounds/have.mp3##v.擁有
letter_h/sounds/he.mp3##pron.他(他的、他自己)
letter_h/sounds/head.mp3##n.頭
letter_h/sounds/headache.mp3##n.頭痛
letter_h/sounds/health.mp3##n.健康
letter_h/sounds/healthy.mp3##adj.健康的
letter_h/sounds/hear.mp3##v.聽見
letter_h/sounds/heart.mp3##n.心臟
letter_h/sounds/heat.mp3##n.熱
letter_h/sounds/heavy.mp3##adj.重的
letter_h/sounds/hello.mp3##n.哈囉
letter_h/sounds/help.mp3##v.幫助
letter_h/sounds/helpful.mp3##adj.有益的
letter_h/sounds/here.mp3##adv.這裡
letter_h/sounds/hi.mp3##n.嗨
letter_h/sounds/hide.mp3##v.藏匿
letter_h/sounds/high.mp3##adj.高的
letter_h/sounds/hill.mp3##n.山丘
letter_h/sounds/history.mp3##n.歷史
letter_h/sounds/hit.mp3##v.打
letter_h/sounds/hobby.mp3##n.嗜好
letter_h/sounds/hold.mp3##v.拿
letter_h/sounds/holiday.mp3##n.假日
letter_h/sounds/home.mp3##n.家；在家
letter_h/sounds/homework.mp3##n.回家作業
letter_h/sounds/honest.mp3##adj.誠實的
letter_h/sounds/hope.mp3##v.希望
letter_h/sounds/horse.mp3##n.馬
letter_h/sounds/hospital.mp3##n.醫院
letter_h/sounds/hot.mp3##adj.熱的
letter_h/sounds/hot_dog.mp3##n.熱狗
letter_h/sounds/hotel.mp3##n.旅館
letter_h/sounds/hour.mp3##n.小時
letter_h/sounds/house.mp3##n.房子
letter_h/sounds/how.mp3##adv.如何
letter_h/sounds/however.mp3##adv.無論如何
letter_h/sounds/hundred.mp3##n.百
letter_h/sounds/hungry.mp3##adj.饑餓的
letter_h/sounds/hurry.mp3##n.趕快急促
letter_h/sounds/hurt.mp3##v.傷害
letter_h/sounds/husband.mp3##n.丈夫
letter_i/sounds/i.mp3##pron.我(我的,我自己)
letter_i/sounds/ice.mp3##n.冰
letter_i/sounds/ice_cream.mp3##n.冰淇淋
letter_i/sounds/idea.mp3##n.點子
letter_i/sounds/if.mp3##conj.如果
letter_i/sounds/ignore.mp3##v.忽略;疏忽
letter_i/sounds/importance.mp3##n.重要
letter_i/sounds/important.mp3##adj.重要的
letter_i/sounds/in.mp3##prep.在~裡面
letter_i/sounds/income.mp3##n.收入
letter_i/sounds/increase.mp3##v.增加
letter_i/sounds/indicate.mp3##v.指示
letter_i/sounds/information.mp3##n.資訊;訊息
letter_i/sounds/inside.mp3##adv.在裡面
letter_i/sounds/insist.mp3##v.堅持
letter_i/sounds/interest.mp3##n.興趣
letter_i/sounds/interested.mp3##adj.感到興趣的
letter_i/sounds/interesting.mp3##adj.有趣的
letter_i/sounds/internet.mp3##n.網際網路
letter_i/sounds/into.mp3##n.進入
letter_i/sounds/island.mp3##n.島嶼
letter_i/sounds/it.mp3##pron.它(它的、它自己的)
letter_j/sounds/jacket.mp3##n.夾克
letter_j/sounds/january.mp3##n.一月
letter_j/sounds/jeans.mp3##n.牛仔褲
letter_j/sounds/job.mp3##n.職業、工作
letter_j/sounds/jog.mp3##v.慢跑
letter_j/sounds/join.mp3##v.參與
letter_j/sounds/joy.mp3##n.喜悅
letter_j/sounds/juice.mp3##n.果汁
letter_j/sounds/July.mp3##n.七月
letter_j/sounds/jump.mp3##v.跳
letter_j/sounds/June.mp3##n.六月
letter_j/sounds/junior_high_school.mp3##n.國中
letter_j/sounds/just.mp3##adv.只是
letter_k/sounds/keep.mp3##v.保持
letter_k/sounds/key.mp3##n.鑰匙
letter_k/sounds/kick.mp3##v.踢
letter_k/sounds/kid.mp3##n.小孩
letter_k/sounds/kill.mp3##v.殺
letter_k/sounds/kilogram.mp3##n.公斤
letter_k/sounds/kilometer.mp3##n.公斤
letter_k/sounds/kind.mp3##adj.和善的n.種類
letter_k/sounds/king.mp3##n.國王
letter_k/sounds/kiss.mp3##v.親吻
letter_k/sounds/kitchen.mp3##n.廚房
letter_k/sounds/kite.mp3##n.風箏
letter_k/sounds/knee.mp3##n.膝蓋
letter_k/sounds/knife.mp3##n.刀子
letter_k/sounds/knock.mp3##v.敲
letter_k/sounds/know.mp3##v.知道
letter_k/sounds/knowledge.mp3##n.知識
letter_l/sounds/lake.mp3##n.湖
letter_l/sounds/lamp.mp3##n.燈
letter_l/sounds/land.mp3##n.土地
letter_l/sounds/language.mp3##n.語言
letter_l/sounds/large.mp3##adj.大的
letter_l/sounds/last.mp3##adj.最後的
letter_l/sounds/late.mp3##adj.遲的
letter_l/sounds/later.mp3##adv.稍後
letter_l/sounds/latest.mp3##adj.最近的;adv.最新
letter_l/sounds/latter.mp3##adj.late比較級;後半的
letter_l/sounds/laugh.mp3##v.笑
letter_l/sounds/lazy.mp3##adj.懶惰的
letter_l/sounds/lead.mp3##v.帶領
letter_l/sounds/leader.mp3##n.領導者
letter_l/sounds/leaf.mp3##n.樹葉
letter_l/sounds/learn.mp3##v.學習
letter_l/sounds/least.mp3##adv.最少
letter_l/sounds/leave.mp3##v.離開
letter_l/sounds/left.mp3##adv.向左;左邊
letter_l/sounds/leg.mp3##n.腿
letter_l/sounds/lemon.mp3##n.檸檬
letter_l/sounds/lend.mp3##v.借出
letter_l/sounds/less.mp3##adj.較少的
letter_l/sounds/lesson.mp3##n.課程
letter_l/sounds/let.mp3##v.讓
letter_l/sounds/letter.mp3##n.信
letter_l/sounds/level.mp3##n.程度;水準
letter_l/sounds/library.mp3##n.圖書館
letter_l/sounds/lick.mp3##v.舔
letter_l/sounds/lie.mp3##n.v.說謊
letter_l/sounds/life.mp3##n.一生
letter_l/sounds/light.mp3##n.光線v.點亮
letter_l/sounds/like.mp3##v.喜歡
letter_l/sounds/likely.mp3##adv.好像
letter_l/sounds/line.mp3##n.線
letter_l/sounds/lion.mp3##n.獅子
letter_l/sounds/lip.mp3##n.嘴唇
letter_l/sounds/list.mp3##n.名單
letter_l/sounds/listen.mp3##v.聽
letter_l/sounds/liter.mp3##n.公升
letter_l/sounds/little.mp3##adj.一點
letter_l/sounds/live.mp3##v.生活
letter_l/sounds/living_room.mp3##n.客廳
letter_l/sounds/lonely.mp3##adj.寂寞的
letter_l/sounds/long.mp3##adj.長的;久的
letter_l/sounds/look.mp3##v.看
letter_l/sounds/lose.mp3##v.失去
letter_l/sounds/loud.mp3##adj.大聲的
letter_l/sounds/love.mp3##v.喜愛
letter_l/sounds/low.mp3##adj.低的;adv.低地
letter_l/sounds/lucky.mp3##adj.幸運的
letter_l/sounds/lunch.mp3##n.午餐
letter_m/sounds/machine.mp3##n.機器
letter_m/sounds/magic.mp3##adj.神奇的
letter_m/sounds/mail.mp3##n.郵件
letter_m/sounds/mailman.mp3##n.郵差
letter_m/sounds/major.mp3##adj.主要的
letter_m/sounds/make.mp3##v.做；決定
letter_m/sounds/man.mp3##n.男人
letter_m/sounds/many.mp3##adj.許多的
letter_m/sounds/map.mp3##n.地圖
letter_m/sounds/March.mp3##n.三月
letter_m/sounds/mark.mp3##v.做上記號
letter_m/sounds/market.mp3##n.市場
letter_m/sounds/married.mp3##adj.結婚的
letter_m/sounds/marvelous.mp3##adj.了不起
letter_m/sounds/master.mp3##n.主人
letter_m/sounds/match.mp3##v.搭配;n.火柴
letter_m/sounds/math.mp3##n.數學
letter_m/sounds/matter.mp3##v.重要
letter_m/sounds/may(might).mp3##modalv.可能
letter_m/sounds/May.mp3##n.五月
letter_m/sounds/maybe.mp3##adv.可能
letter_m/sounds/meal.mp3##n.餐
letter_m/sounds/mean.mp3##v.意指
letter_m/sounds/meat.mp3##n.肉
letter_m/sounds/media.mp3##n.媒體
letter_m/sounds/medicine.mp3##n.藥物
letter_m/sounds/medium.mp3##adj.中間
letter_m/sounds/meet.mp3##v.相遇
letter_m/sounds/meeting.mp3##n.會議
letter_m/sounds/menu.mp3##n.菜單
letter_m/sounds/mile.mp3##n.英哩
letter_m/sounds/milk.mp3##n.牛奶
letter_m/sounds/million.mp3##n.百萬
letter_m/sounds/mind.mp3##n.心;v.介意
letter_m/sounds/minute.mp3##n.分鐘
letter_m/sounds/Miss.mp3##n.小姐
letter_m/sounds/miss_1.mp3##v.錯過；想念
letter_m/sounds/mistake.mp3##n.錯誤
letter_m/sounds/modern.mp3##adj.現代的
letter_m/sounds/moment.mp3##n.時刻
letter_m/sounds/Monday.mp3##n.星期一
letter_m/sounds/money.mp3##n.錢
letter_m/sounds/monkey.mp3##n.猴子
letter_m/sounds/month.mp3##n.月份
letter_m/sounds/moon.mp3##n.月亮
letter_m/sounds/more.mp3##adj.更多
letter_m/sounds/morning.mp3##n.早晨
letter_m/sounds/most.mp3##adj.最多的
letter_m/sounds/mother.mp3##n.媽媽
letter_m/sounds/motorcycle.mp3##n.機車
letter_m/sounds/mountain.mp3##n.山
letter_m/sounds/mouse.mp3##n.老鼠
letter_m/sounds/mouth.mp3##n.嘴
letter_m/sounds/move.mp3##v.搬家；感動；搬移
letter_m/sounds/movie.mp3##n.電影
letter_m/sounds/Mr..mp3##n.先生
letter_m/sounds/Mrs..mp3##n.太太
letter_m/sounds/Ms..mp3##n.小姐或太太
letter_m/sounds/much.mp3##pron.多
letter_m/sounds/museum.mp3##n.博物館
letter_m/sounds/music.mp3##n.音樂
letter_m/sounds/must.mp3##modalv.必須
letter_n/sounds/name.mp3##n.名字
letter_n/sounds/national.mp3##adj.國家的
letter_n/sounds/near.mp3##prep.近
letter_n/sounds/neck.mp3##n.脖子
letter_n/sounds/need.mp3##v.需要
letter_n/sounds/never.mp3##adv.從不
letter_n/sounds/new.mp3##adj.新的
letter_n/sounds/news.mp3##n.新聞
letter_n/sounds/next.mp3##adj.下一個
letter_n/sounds/nice.mp3##adj.好的
letter_n/sounds/night.mp3##n.夜晚
letter_n/sounds/nine.mp3##n.九
letter_n/sounds/nineteen.mp3##n.十九
letter_n/sounds/ninety.mp3##n.九十
letter_n/sounds/ninth.mp3##n.第九
letter_n/sounds/no.mp3##adv.不
letter_n/sounds/nobody.mp3##pron.沒有人
letter_n/sounds/nod.mp3##v.點頭
letter_n/sounds/noise.mp3##n.噪音
letter_n/sounds/noodle.mp3##n.麵條
letter_n/sounds/noon.mp3##n.中午
letter_n/sounds/north.mp3##n.北方
letter_n/sounds/nose.mp3##n.鼻子
letter_n/sounds/not.mp3##adv.不是
letter_n/sounds/notebook.mp3##n.筆記本
letter_n/sounds/nothing.mp3##pron.沒有
letter_n/sounds/notice.mp3##v.注意
letter_n/sounds/novel.mp3##n.小說
letter_n/sounds/November.mp3##n.十一月
letter_n/sounds/now.mp3##adv.現在
letter_n/sounds/number.mp3##n.數字
letter_n/sounds/nurse.mp3##n.護士
letter_o/sounds/oclock.mp3##n.點鐘
letter_o/sounds/October.mp3##n.十月
letter_o/sounds/of.mp3##prep.屬於~的
letter_o/sounds/off.mp3##adv.中斷(水電)
letter_o/sounds/office.mp3##n.辦公室
letter_o/sounds/officer.mp3##n.官員
letter_o/sounds/often.mp3##adv.經常
letter_o/sounds/oil.mp3##n.油
letter_o/sounds/OK.mp3##adj.一切沒問題
letter_o/sounds/old.mp3##adj.老的
letter_o/sounds/on.mp3##prep.在~上面
letter_o/sounds/once.mp3##adv.一次
letter_o/sounds/one.mp3##n.一
letter_o/sounds/oneself.mp3##pron.~自己
letter_o/sounds/only.mp3##adv.只有
letter_o/sounds/open.mp3##v.打開
letter_o/sounds/or.mp3##conj.或者
letter_o/sounds/orange.mp3##adj.柳丁
letter_o/sounds/order.mp3##v.點餐
letter_o/sounds/other.mp3##adj.其他的
letter_o/sounds/out.mp3##adv.出去
letter_o/sounds/outside.mp3##adv.外面
letter_o/sounds/over.mp3##adv.外面
letter_o/sounds/own.mp3##v.擁有
letter_p/sounds/p.m..mp3##abbr.午後
letter_p/sounds/pack.mp3##n.一包
letter_p/sounds/package.mp3##n.包裹
letter_p/sounds/page.mp3##n.頁
letter_p/sounds/paint.mp3##v.油漆
letter_p/sounds/pair.mp3##n.一雙
letter_p/sounds/pants.mp3##n.褲子
letter_p/sounds/paper.mp3##n.紙
letter_p/sounds/parent.mp3##n.雙親之一
letter_p/sounds/park.mp3##n.公園
letter_p/sounds/part.mp3##n.部分
letter_p/sounds/party.mp3##n.宴會
letter_p/sounds/pass.mp3##v.通過，經過
letter_p/sounds/past.mp3##n.過去
letter_p/sounds/pay.mp3##v.付賬
letter_p/sounds/PE.mp3##n.體育
letter_p/sounds/pen.mp3##n.筆
letter_p/sounds/pencil.mp3##n.鉛筆
letter_p/sounds/people.mp3##n.人們
letter_p/sounds/perhaps.mp3##adv.或許
letter_p/sounds/person.mp3##n.人
letter_p/sounds/pet.mp3##n.寵物
letter_p/sounds/photo.mp3##n.照片
letter_p/sounds/physics.mp3##n.物理學
letter_p/sounds/piano.mp3##n.鋼琴
letter_p/sounds/pick.mp3##v.撿拾
letter_p/sounds/picnic.mp3##v.野餐
letter_p/sounds/picture.mp3##n.圖畫
letter_p/sounds/pie.mp3##n.派
letter_p/sounds/piece.mp3##n.一張，一片
letter_p/sounds/pig.mp3##n.豬
letter_p/sounds/pink.mp3##adj.粉紅色
letter_p/sounds/pizza.mp3##n.披薩
letter_p/sounds/place.mp3##n.地方
letter_p/sounds/plan.mp3##n.計畫
letter_p/sounds/planet.mp3##n.行星
letter_p/sounds/play.mp3##n.玩
letter_p/sounds/player.mp3##n.球員
letter_p/sounds/playground.mp3##n.運動場，遊戲場
letter_p/sounds/please.mp3##v.請求
letter_p/sounds/pocket.mp3##n.口袋
letter_p/sounds/point.mp3##n.觀點，點
letter_p/sounds/police.mp3##n.警方
letter_p/sounds/polite.mp3##adj.禮貌的
letter_p/sounds/poor.mp3##adj.貧窮的，可憐的
letter_p/sounds/popcorn.mp3##n.爆米花
letter_p/sounds/popular.mp3##adj.受歡迎的
letter_p/sounds/pork.mp3##n.豬肉
letter_p/sounds/possible.mp3##adj.有可能的
letter_p/sounds/post office.mp3##n.郵局
letter_p/sounds/postcard.mp3##n.明信片
letter_p/sounds/pound.mp3##n.磅
letter_p/sounds/powder.mp3##n.粉末
letter_p/sounds/practice.mp3##n.練習
letter_p/sounds/prepare.mp3##v.準備
letter_p/sounds/present.mp3##n.當下，禮物adj.出席
letter_p/sounds/pretty.mp3##adj.漂亮的
letter_p/sounds/price.mp3##n.價錢
letter_p/sounds/problem.mp3##n.問題
letter_p/sounds/professor.mp3##n.教授
letter_p/sounds/program.mp3##n.節目，計畫
letter_p/sounds/proud.mp3##adj.驕傲的
letter_p/sounds/public.mp3##adj.公共的
letter_p/sounds/pull.mp3##v.拉
letter_p/sounds/purple.mp3##adj.紫色的
letter_p/sounds/push.mp3##v.推
letter_p/sounds/put.mp3##v.放
letter_q/sounds/queen.mp3##n.皇后
letter_q/sounds/question.mp3##n.問題
letter_q/sounds/quick.mp3##adj.快速的
letter_q/sounds/quiet.mp3##adj.安靜的
letter_q/sounds/quite.mp3##adv.非常，相當
letter_r/sounds/rabbit.mp3##n.兔子
letter_r/sounds/race.mp3##n.競賽
letter_r/sounds/radio.mp3##n.收音機
letter_r/sounds/railway.mp3##n.鐵路
letter_r/sounds/rain.mp3##n.雨
letter_r/sounds/rainbow.mp3##n.彩虹
letter_r/sounds/rainy.mp3##adj.下雨的
letter_r/sounds/reach.mp3##v.抵達
letter_r/sounds/read.mp3##v.讀
letter_r/sounds/ready.mp3##adj.準備好
letter_r/sounds/real.mp3##adj.真實的
letter_r/sounds/really.mp3##adv.真地
letter_r/sounds/recorder.mp3##n.錄音機
letter_r/sounds/recycle.mp3##v.回收
letter_r/sounds/red.mp3##adj.紅色
letter_r/sounds/refrigerator.mp3##n.冰箱
letter_r/sounds/regular.mp3##adj.有規則的
letter_r/sounds/remember.mp3##v.記得
letter_r/sounds/repeat.mp3##v.重複
letter_r/sounds/report.mp3##n.報告
letter_r/sounds/reporter.mp3##n.記者
letter_r/sounds/rest.mp3##n.休息；其他
letter_r/sounds/restaurant.mp3##n.餐廳
letter_r/sounds/restroom.mp3##n.洗手間
letter_r/sounds/result.mp3##n.結果
letter_r/sounds/return.mp3##v.回來
letter_r/sounds/rice.mp3##n.米
letter_r/sounds/rich.mp3##adj.富有的
letter_r/sounds/ride.mp3##v.騎
letter_r/sounds/right.mp3##n.正確adj.右邊
letter_r/sounds/ring.mp3##n.戒指
letter_r/sounds/river.mp3##n.河流
letter_r/sounds/road.mp3##n.道路
letter_r/sounds/ROC.mp3##n.中華民國
letter_r/sounds/rock.mp3##n.岩石
letter_r/sounds/role.mp3##n.角色
letter_r/sounds/Roller-blade.mp3##v.溜直排輪
letter_r/sounds/room.mp3##n.房間
letter_r/sounds/root.mp3##n.根
letter_r/sounds/rose.mp3##n.玫瑰
letter_r/sounds/round.mp3##adj.圓的
letter_r/sounds/row.mp3##n.排；槳v.爭吵
letter_r/sounds/rule.mp3##n.規則
letter_r/sounds/ruler.mp3##n.尺
letter_r/sounds/run.mp3##v.跑
letter_s/sounds/sad.mp3##adj.傷心的
letter_s/sounds/safe.mp3##adj.安全的
letter_s/sounds/salad.mp3##n.沙拉
letter_s/sounds/sale.mp3##n.廉售
letter_s/sounds/salt.mp3##n.鹽巴
letter_s/sounds/same.mp3##adj.同樣的
letter_s/sounds/sand.mp3##n.沙子
letter_s/sounds/sandwich.mp3##n.三明治
letter_s/sounds/Saturday.mp3##n.星期六
letter_s/sounds/save.mp3##v.儲存
letter_s/sounds/say.mp3##v.說
letter_s/sounds/scene.mp3##n.風景;舞台
letter_s/sounds/scenery.mp3##n.景色
letter_s/sounds/school.mp3##n.學校
letter_s/sounds/scooter.mp3##n.滑板車
letter_s/sounds/sea.mp3##n.海
letter_s/sounds/season.mp3##n.季節
letter_s/sounds/seat.mp3##n.位子
letter_s/sounds/second.mp3##adj.第二；秒
letter_s/sounds/see.mp3##v.看見
letter_s/sounds/seed.mp3##n.種子
letter_s/sounds/seek.mp3##v.追尋
letter_s/sounds/seldom.mp3##adv.很少
letter_s/sounds/sell.mp3##v.賣
letter_s/sounds/send.mp3##v.傳送
letter_s/sounds/senior_high_school.mp3##n.高中
letter_s/sounds/sense.mp3##n.感覺
letter_s/sounds/sentence.mp3##n.句子
letter_s/sounds/September.mp3##n.九月
letter_s/sounds/serious.mp3##adj.嚴重的認真的
letter_s/sounds/set.mp3##n.;v.台;設定
letter_s/sounds/seven.mp3##n.七
letter_s/sounds/seventeen.mp3##n.十七
letter_s/sounds/seventh.mp3##n.第七
letter_s/sounds/seventy.mp3##n.七十
letter_s/sounds/several.mp3##adj.好幾個
letter_s/sounds/shall.mp3##modalv將要
letter_s/sounds/shape.mp3##n.形狀
letter_s/sounds/share.mp3##v.分享
letter_s/sounds/sharp.mp3##adj.銳利的
letter_s/sounds/she(her,hers,herself).mp3##pron她(她的,她自己)
letter_s/sounds/sheep.mp3##n.綿羊
letter_s/sounds/ship.mp3##n.船
letter_s/sounds/shirt.mp3##n.襯衫
letter_s/sounds/shoe(s).mp3##n.鞋子
letter_s/sounds/shoot.mp3##v.射擊
letter_s/sounds/shop.mp3##n.商店
letter_s/sounds/shopkeeper.mp3##n.店主
letter_s/sounds/short.mp3##adj.短的
letter_s/sounds/should.mp3##助動詞.應該
letter_s/sounds/shoulder.mp3##n.肩膀
letter_s/sounds/show.mp3##n.;v.表演;展示
letter_s/sounds/shy.mp3##adj.害羞的
letter_s/sounds/sick.mp3##adj.生病的
letter_s/sounds/side.mp3##n.旁邊
letter_s/sounds/sidewalk.mp3##n.人行道
letter_s/sounds/sight.mp3##n.景象;視力
letter_s/sounds/simple.mp3##adj.簡單的
letter_s/sounds/since.mp3##prep自從
letter_s/sounds/sing.mp3##v.唱歌
letter_s/sounds/singer.mp3##n.歌手
letter_s/sounds/sir.mp3##n.先生
letter_s/sounds/sister.mp3##n.姊妹
letter_s/sounds/sit.mp3##v.坐
letter_s/sounds/six.mp3##n.六
letter_s/sounds/sixteen.mp3##n.十六
letter_s/sounds/sixth.mp3##n.第六
letter_s/sounds/sixty.mp3##n.六十
letter_s/sounds/size.mp3##n.尺寸
letter_s/sounds/skate.mp3##v.溜冰
letter_s/sounds/ski.mp3##v.滑雪
letter_s/sounds/skillful.mp3##adj.熟練的
letter_s/sounds/skirt.mp3##n.裙子
letter_s/sounds/sky.mp3##n.天空
letter_s/sounds/sleep.mp3##v.睡覺
letter_s/sounds/sleepy.mp3##adj.想睡的
letter_s/sounds/slow.mp3##adj.緩慢的
letter_s/sounds/small.mp3##adj.小的
letter_s/sounds/smart.mp3##adj.聰明的
letter_s/sounds/smell.mp3##v.聞到
letter_s/sounds/smile.mp3##v.微笑
letter_s/sounds/smoke.mp3##v.抽煙
letter_s/sounds/snack.mp3##n.點心
letter_s/sounds/snake.mp3##n.蛇
letter_s/sounds/snow.mp3##v.下雪
letter_s/sounds/so.mp3##adv.如此
letter_s/sounds/soap.mp3##n.肥皂
letter_s/sounds/socks.mp3##n.襪子
letter_s/sounds/sofa.mp3##n.沙發
letter_s/sounds/some.mp3##adj.一些
letter_s/sounds/someone(somebody).mp3##pron一些人
letter_s/sounds/something.mp3##pron.一些事
letter_s/sounds/sometimes.mp3##adv.有時候
letter_s/sounds/somewhere.mp3##pron.某處
letter_s/sounds/son.mp3##n.兒子
letter_s/sounds/song.mp3##n.歌曲
letter_s/sounds/soon.mp3##adv.很快
letter_s/sounds/sorry.mp3##adj.抱歉;遺憾
letter_s/sounds/soul.mp3##n.靈魂
letter_s/sounds/sound.mp3##v.聽起來
letter_s/sounds/soup.mp3##n.湯
letter_s/sounds/south.mp3##n.南方
letter_s/sounds/space.mp3##n.空間;太空
letter_s/sounds/speak.mp3##v.說
letter_s/sounds/special.mp3##adj.特別的
letter_s/sounds/speed.mp3##n.速度
letter_s/sounds/spell.mp3##v.拼字
letter_s/sounds/spend.mp3##v.花費
letter_s/sounds/spoon.mp3##n.湯匙
letter_s/sounds/sports.mp3##n.運動
letter_s/sounds/spring.mp3##n.春天
letter_s/sounds/square.mp3##n.廣場;正方形
letter_s/sounds/stand.mp3##v.站
letter_s/sounds/star.mp3##n.星星
letter_s/sounds/start.mp3##v.開始
letter_s/sounds/state.mp3##n.州
letter_s/sounds/station.mp3##n.車站
letter_s/sounds/stationery.mp3##n.文具
letter_s/sounds/stay.mp3##v.停留
letter_s/sounds/steak.mp3##n.牛排
letter_s/sounds/step.mp3##n.;v.步;踐踏
letter_s/sounds/still.mp3##adv.仍然
letter_s/sounds/stomach.mp3##n.胃
letter_s/sounds/stone.mp3##n.石頭
letter_s/sounds/stop.mp3##v.停止
letter_s/sounds/store.mp3##n.商店
letter_s/sounds/story.mp3##n.故事
letter_s/sounds/strange.mp3##adj.奇怪的
letter_s/sounds/stranger.mp3##n.陌生人
letter_s/sounds/street.mp3##n.街道
letter_s/sounds/strong.mp3##adj.強壯的
letter_s/sounds/student.mp3##n.學生
letter_s/sounds/study.mp3##v.研讀
letter_s/sounds/stupid.mp3##adj.愚笨的
letter_s/sounds/subject.mp3##n.學科;主詞
letter_s/sounds/successful.mp3##adj.成功的
letter_s/sounds/sugar.mp3##n.糖
letter_s/sounds/suggest.mp3##v.建議
letter_s/sounds/summer.mp3##n.夏天
letter_s/sounds/sun.mp3##n.太陽
letter_s/sounds/Sunday.mp3##n.星期日
letter_s/sounds/sunny.mp3##adj.晴天的
letter_s/sounds/super.mp3##adj.超級的
letter_s/sounds/supermarket.mp3##n.超級市場
letter_s/sounds/sure.mp3##adj.確定的
letter_s/sounds/surf.mp3##v.上網
letter_s/sounds/surprise.mp3##v.驚訝
letter_s/sounds/surprised.mp3##adj.感到驚訝的
letter_s/sounds/sweater.mp3##n.毛衣
letter_s/sounds/sweet.mp3##adj.甜的;貼心的
letter_s/sounds/swim.mp3##v.游泳
letter_s/sounds/system.mp3##n.系統
letter_t/sounds/table.mp3##n.桌子
letter_t/sounds/Taiwan.mp3##n.台灣
letter_t/sounds/take.mp3##v.拿；帶
letter_t/sounds/talent.mp3##n.天分
letter_t/sounds/talk.mp3##v.談話
letter_t/sounds/tall.mp3##adj.高的
letter_t/sounds/tape.mp3##n.錄音帶；膠帶
letter_t/sounds/taste.mp3##v.嚐起來n.品味
letter_t/sounds/taxi.mp3##n.計程車
letter_t/sounds/tea.mp3##n.茶
letter_t/sounds/teach.mp3##v.教書
letter_t/sounds/teacher.mp3##n.老師
letter_t/sounds/team.mp3##n.團隊
letter_t/sounds/teenager.mp3##n.青少年
letter_t/sounds/telephone.mp3##n.電話
letter_t/sounds/television.mp3##n.電視
letter_t/sounds/tell.mp3##v.說
letter_t/sounds/ten.mp3##n.十
letter_t/sounds/tennis.mp3##n.網球
letter_t/sounds/tenth.mp3##n.第十
letter_t/sounds/terrific.mp3##adj.好極了
letter_t/sounds/test.mp3##n.測驗
letter_t/sounds/than.mp3##conj.比
letter_t/sounds/thank.mp3##v.感謝
letter_t/sounds/Thankgiving.mp3##n.感恩節
letter_t/sounds/that.mp3##pron.那
letter_t/sounds/the.mp3##art.這；那
letter_t/sounds/theater.mp3##n.戲院
letter_t/sounds/then.mp3##adv.那時
letter_t/sounds/there.mp3##adv.那裡
letter_t/sounds/therefore.mp3##adv.因此
letter_t/sounds/these.mp3##pron.這些
letter_t/sounds/they.mp3##pron.他們(他們的、他們自己)
letter_t/sounds/thick.mp3##adj.厚的
letter_t/sounds/thin.mp3##adj.瘦的
letter_t/sounds/thing.mp3##n.東西
letter_t/sounds/think.mp3##v.想
letter_t/sounds/third.mp3##n.第三
letter_t/sounds/thirsty.mp3##adj.口渴的
letter_t/sounds/thirteen.mp3##n.十三
letter_t/sounds/thirty.mp3##n.三十
letter_t/sounds/this.mp3##pron.這個
letter_t/sounds/those.mp3##pron.那些
letter_t/sounds/though.mp3##conj.雖然
letter_t/sounds/thousand.mp3##n.千
letter_t/sounds/three.mp3##n.三
letter_t/sounds/Thursday.mp3##n.星期四
letter_t/sounds/ticket.mp3##n.票　
letter_t/sounds/tiger.mp3##n.老虎　
letter_t/sounds/time.mp3##n.時間　
letter_t/sounds/tip.mp3##n.訣竅　
letter_t/sounds/tired.mp3##adj.疲累的　
letter_t/sounds/to.mp3##prep.到、向　
letter_t/sounds/today.mp3##adv.今天n.今天　
letter_t/sounds/together.mp3##adv.一起　
letter_t/sounds/tomato.mp3##n.番茄　
letter_t/sounds/tomorrow.mp3##adv.明天n.明天　
letter_t/sounds/tonight.mp3##adv.今晚n.今晚　
letter_t/sounds/too.mp3##adv.太；也　
letter_t/sounds/tooth.mp3##n.牙齒　
letter_t/sounds/top.mp3##n.頂端　
letter_t/sounds/total.mp3##n.總數　
letter_t/sounds/touch.mp3##v.接觸；碰到　
letter_t/sounds/towel.mp3##n.毛巾　
letter_t/sounds/town.mp3##n.城鎮　
letter_t/sounds/toy.mp3##n.玩具　
letter_t/sounds/traffic.mp3##n.交通　
letter_t/sounds/train.mp3##n.火車　
letter_t/sounds/trash.mp3##n.垃圾　
letter_t/sounds/travel.mp3##v.旅行　
letter_t/sounds/tree.mp3##n.樹　
letter_t/sounds/trick.mp3##n.把戲;策略;秘訣　
letter_t/sounds/trip.mp3##n.旅行　
letter_t/sounds/trouble.mp3##n.麻煩　
letter_t/sounds/truck.mp3##n.貨車　
letter_t/sounds/true.mp3##adj.真實的　
letter_t/sounds/try.mp3##v.嘗試　
letter_t/sounds/Tuesday.mp3##n.星期二　
letter_t/sounds/turn.mp3##v.轉向n.輪次　
letter_t/sounds/twelve.mp3##n.十二　
letter_t/sounds/twenty.mp3##n.二十　
letter_t/sounds/twice.mp3##adv.兩次　
letter_t/sounds/two.mp3##n.二　
letter_t/sounds/typhoon.mp3##n.颱風　
letter_u/sounds/umbrella.mp3##n.雨傘
letter_u/sounds/uncle.mp3##n.伯、叔、舅
letter_u/sounds/under.mp3##prep.在底下
letter_u/sounds/understand.mp3##v.了解
letter_u/sounds/unhappy.mp3##adj.不高興的
letter_u/sounds/uniform.mp3##n.制服
letter_u/sounds/university.mp3##n.大學
letter_u/sounds/until.mp3##conj.直到
letter_u/sounds/up.mp3##adv.向上
letter_u/sounds/upper.mp3##art.一個
letter_u/sounds/USA.mp3##n.美國
letter_u/sounds/use.mp3##v.使用
letter_u/sounds/useful.mp3##adj.有用的
letter_u/sounds/usually.mp3##adv.經常
letter_v/sounds/vacation.mp3##n.假期
letter_v/sounds/Valentine.mp3##n.情人節
letter_v/sounds/vegetable.mp3##n.蔬菜
letter_v/sounds/vendor.mp3##n.攤販
letter_v/sounds/very.mp3##adv.非常
letter_v/sounds/video.mp3##n.影片
letter_v/sounds/visit.mp3##v.拜訪
letter_v/sounds/voice.mp3##n.聲音
letter_w/sounds/wait.mp3##v.等待
letter_w/sounds/waiter.mp3##n.服務生
letter_w/sounds/waitress.mp3##n.女服務生
letter_w/sounds/wake.mp3##v.喚醒
letter_w/sounds/walk.mp3##v.走路
letter_w/sounds/wall.mp3##n.牆壁
letter_w/sounds/want.mp3##v.想要
letter_w/sounds/warm.mp3##adj.溫暖
letter_w/sounds/wash.mp3##v.洗
letter_w/sounds/watch.mp3##v.看
letter_w/sounds/water.mp3##n.水
letter_w/sounds/waterfall.mp3##n.瀑布
letter_w/sounds/way.mp3##n.方法、道路
letter_w/sounds/we(us,our,ours,ourselves).mp3##pron.我們(我們的、我們自己)
letter_w/sounds/weak.mp3##adj.虛弱的
letter_w/sounds/wear.mp3##v.穿
letter_w/sounds/weather.mp3##n.天氣
letter_w/sounds/Wednesday.mp3##n.星期三
letter_w/sounds/week.mp3##n.週
letter_w/sounds/weekday.mp3##n.工作日
letter_w/sounds/weekend.mp3##n.週末
letter_w/sounds/welcome.mp3##v.歡迎
letter_w/sounds/well.mp3##adv.很好
letter_w/sounds/west.mp3##n.西方
letter_w/sounds/wet.mp3##adj.濕的
letter_w/sounds/what.mp3##pron.什麼
letter_w/sounds/when.mp3##adv.何時
letter_w/sounds/where.mp3##adv.哪裡
letter_w/sounds/whether.mp3##conj.無論
letter_w/sounds/which.mp3##pron.哪一個
letter_w/sounds/white.mp3##adj.白色
letter_w/sounds/who.mp3##pron.誰
letter_w/sounds/whose.mp3##pron.誰的
letter_w/sounds/why.mp3##adv.為什麼
letter_w/sounds/wife.mp3##n.妻子
letter_w/sounds/wild.mp3##adj.野生的
letter_w/sounds/will(would).mp3##modalv.將要
letter_w/sounds/win.mp3##v.嬴
letter_w/sounds/wind.mp3##n.風
letter_w/sounds/window.mp3##n.窗戶
letter_w/sounds/windy.mp3##adj.多風的
letter_w/sounds/winter.mp3##n.冬天
letter_w/sounds/wise.mp3##adj.有智慧的
letter_w/sounds/wish.mp3##v.但願
letter_w/sounds/with.mp3##prep.與
letter_w/sounds/without.mp3##prep.沒有
letter_w/sounds/woman.mp3##n.女人
letter_w/sounds/wonderful.mp3##adj.很棒的
letter_w/sounds/wood.mp3##n.木材
letter_w/sounds/word.mp3##n.字
letter_w/sounds/work.mp3##v.工作
letter_w/sounds/workbook.mp3##n.作業本
letter_w/sounds/worker.mp3##n.工人
letter_w/sounds/world.mp3##n.世界
letter_w/sounds/worry.mp3##v.擔憂
letter_w/sounds/write.mp3##v.寫
letter_w/sounds/writer.mp3##n.作家
letter_w/sounds/wrong.mp3##adj.錯誤的
letter_y/sounds/year.mp3##n.年
letter_y/sounds/yellow.mp3##adj.黃色
letter_y/sounds/yes(yeah).mp3##adv.是的
letter_y/sounds/yesterday.mp3##adv.昨天；n.昨天
letter_y/sounds/yet.mp3##adv.尚未
letter_y/sounds/you(your,yours,yourself,yourselves).mp3##pron.你/你們(你的/你們的、你自己/你自己的)
letter_y/sounds/young.mp3##adj.年輕的
letter_z/sounds/zoo.mp3##n.動物園
-----*/}.toString().replace(/\r/g,"").slice("function(){/*--這一行請勿更改--".length+1,-9);
